# -*- coding: utf-8 -*-
"""Gestor de Descargas de YouTube multi-playlist con yt-dlp y evasión de bloqueos bot."""

import os
import json
import glob
import shutil
import subprocess
from .config import BASE_DIR, load_config
from .task_manager import task_manager
from .sync_engine import consolidate_and_deduplicate


def _convert_json_cookies_to_netscape(json_path, netscape_path):
    """Convierte cookies exportadas desde extensiones (Cookie Editor) al formato Netscape que yt-dlp entiende."""
    try:
        with open(json_path, "r", encoding="utf-8") as f:
            data = json.load(f)

        cookies = data.get("cookies", data) if isinstance(data, dict) else data
        if not isinstance(cookies, list) or len(cookies) == 0:
            return False

        lines = [
            "# Netscape HTTP Cookie File",
            "# https://curl.se/docs/http-cookies.html",
            "# Auto-generated by MusicSync Studio from JSON export",
            ""
        ]

        for c in cookies:
            domain = c.get("domain", "")
            flag = "TRUE" if domain.startswith(".") else "FALSE"
            path = c.get("path", "/")
            secure = "TRUE" if c.get("secure", False) else "FALSE"
            expires = str(int(c.get("expirationDate", 0)))
            name = c.get("name", "")
            value = c.get("value", "")
            http_only = "#HttpOnly_" if c.get("httpOnly", False) else ""
            lines.append(f"{http_only}{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")

        with open(netscape_path, "w", encoding="utf-8", newline="\n") as f:
            f.write("\n".join(lines) + "\n")

        return True
    except Exception as e:
        print(f"[!] Error convirtiendo cookies JSON: {e}")
        return False


def _ensure_fresh_cookies():
    """Busca archivos .json de cookies en el directorio base y los convierte automáticamente a Netscape."""
    netscape_path = os.path.join(BASE_DIR, "cookies_netscape.txt")

    # Buscar archivos JSON de cookies (ej: www.youtube.com_12-08-2026.json)
    json_patterns = [
        os.path.join(BASE_DIR, "*.youtube.com*.json"),
        os.path.join(BASE_DIR, "youtube_cookies*.json"),
        os.path.join(BASE_DIR, "cookies*.json"),
    ]

    newest_json = None
    newest_mtime = 0

    for pattern in json_patterns:
        for fpath in glob.glob(pattern):
            # Excluir config.json
            if os.path.basename(fpath).lower() == "config.json":
                continue
            mtime = os.path.getmtime(fpath)
            if mtime > newest_mtime:
                newest_mtime = mtime
                newest_json = fpath

    if newest_json:
        # Si el JSON es más nuevo que el Netscape existente, reconvertir
        netscape_mtime = os.path.getmtime(netscape_path) if os.path.exists(netscape_path) else 0
        if newest_mtime > netscape_mtime:
            ok = _convert_json_cookies_to_netscape(newest_json, netscape_path)
            if ok:
                print(f"[*] Cookies actualizadas desde: {os.path.basename(newest_json)}")

    return netscape_path


def download_playlists(progress_callback=None, cancel_event=None):
    ok, conflict_msg = task_manager.register_task("download_task", "DOWNLOAD", "Descargando Playlists")
    if not ok:
        if progress_callback: progress_callback(conflict_msg)
        return False, conflict_msg

    config = load_config()
    playlists = config.get("playlists", [])
    if not playlists:
        task_manager.unregister_task("download_task")
        return False, "No hay playlists configuradas."

    target_dir = config.get("source_folder") or os.path.join(BASE_DIR, "Musica")
    os.makedirs(target_dir, exist_ok=True)

    historial_path = os.path.join(BASE_DIR, config.get("historial_file", "historial.txt"))

    # Auto-detectar y convertir cookies JSON → Netscape
    cookies_path = _ensure_fresh_cookies()

    # Detectar Node.js para runtime de JavaScript de yt-dlp
    has_node = shutil.which("node") is not None

    for pl in playlists:
        if cancel_event and cancel_event.is_set():
            break

        if not pl.get("active", True):
            continue

        url = pl.get("url")
        name = pl.get("name", "Playlist")
        if progress_callback:
            progress_callback(f"[*] Conectando con YouTube para: '{name}'")
            progress_callback(f"[*] Guardando en: {target_dir}")

        cmd = [
            "yt-dlp",
            "--extract-audio",
            "--audio-format", "mp3",
            "--audio-quality", "0",
            "--embed-thumbnail",
            "--embed-metadata",
            "--add-metadata",
            "--download-archive", historial_path,
            "--output", os.path.join(target_dir, "%(artist,creator,uploader)s - %(title)s.%(ext)s"),
            "--no-overwrites",
            "--ignore-errors",
            "--retries", "10",
            "--fragment-retries", "10",
            "--sleep-requests", "1.5",
            "--extractor-args", "youtube:player_client=web"
        ]

        if has_node:
            cmd.extend(["--js-runtimes", "node"])

        # Usar cookies Netscape (siempre preferir archivo sobre --cookies-from-browser)
        if os.path.exists(cookies_path) and os.path.getsize(cookies_path) > 100:
            cmd.extend(["--cookies", cookies_path])

        cmd.append(url)

        try:
            process = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, encoding='utf-8', errors='replace')
            for line in process.stdout:
                line = line.strip()
                if line and progress_callback:
                    if "Sign in to confirm" in line:
                        progress_callback("[!] YouTube solicitó verificación. Renovando cookies podría ayudar...")
                    elif "WARNING" in line and "SABR" in line:
                        continue  # Suprimir warnings SABR que no afectan la descarga
                    else:
                        progress_callback(line)
                if cancel_event and cancel_event.is_set():
                    process.terminate()
                    break
            process.wait()
        except Exception as e:
            if progress_callback:
                progress_callback(f"[!] Error en yt-dlp: {e}")

    task_manager.unregister_task("download_task")
    # Consolidar y desduplicar automáticamente al terminar
    consolidate_and_deduplicate(dry_run=False)
    return True, "Descarga y sincronización completada."
